routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RolePermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('roles', RoleController::class);
    Route::get('roles/{role}/assign-permissions', [RolePermissionController::class, 'index'])->name('roles.show');
    Route::post('roles/{role}/assign-permissions', [RolePermissionController::class, 'assign'])->name('roles.assign-permissions');

    Route::resource('permissions', PermissionController::class);
    Route::get('/assign-role', [UserRoleController::class, 'index'])->name('user_roles.index');
    Route::get('{user}/assign-role', [UserRoleController::class, 'create'])->name('user_roles.create');
    Route::post('/{user}/assign-role', [UserRoleController::class, 'assignRoles'])->name('user_roles.store');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

});

require __DIR__ . '/auth.php';

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Permission extends Model
{
    use HasFactory;
    protected $fillable = ["name","guard_name"];

}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    public function index()
    {
        $permissions = Permission::all();
        return view('permissions.index', compact('permissions'));
    }
    public function create()
    {
        return view('permissions.create');
    }
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|unique:permissions|max:255',
        ]);
        $permission = Permission::create(['name' => $validated['name']]);
        return redirect()->route('permissions.index')
            ->with('success', 'Permission created successfully.');
    }
    public function show(Permission $permission)
    {
        return view('permissions.show', compact('permission'));
    }
    public function edit(Permission $permission)
    {
        return view('permissions.edit', compact('permission'));
    }
    public function update(Request $request, Permission $permission)
    {
        $validated = $request->validate([
            'name' => 'required|unique:permissions,name,' . $permission->id . '|max:255',
        ]);
        $permission->name = $validated['name'];
        $permission->save();
        return redirect()->route('permissions.index')
            ->with('success', 'Permission updated successfully');
    }
    public function destroy(Permission $permission)
    {
        $permission->delete();
        return redirect()->route('permissions.index')
            ->with('success', 'Permission deleted successfully');
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/permissions/create.blade.php
 @extends('layouts.layout')
 @section('title','Ajouter une role')
 @section('space-work')
 <div class="container">
     <h1>Créer une nouvelle permission</h1>
     <form action="{{route('permissions.store')}}" method="POST">
         @csrf
         <div>
         <label for="name">Name</label>
         <input type="text" name="name" id="name" value="{{old('name')}}">
         </div>
         <div>
             <input class="button" type="submit" value="Ajouter">
         </div>
     </form>
     <div>
         @if($errors->any())
         <ul>
           @foreach($errors->all() as $er)
            <li>{{$er}}</li>

            @endforeach
         </ul>



         @endif
     </div>
 </div>
@endsection

resources/views/permissions/edit.blade.php
 @extends('layouts.layout')
 @section('title', 'Modifier une permission')
 @section('space-work')
<div class="container">

    <form action="{{ route('permissions.update', ['permission' => $permission->id]) }}" method="POST">
        @csrf
        @method('PUT')
        <h3 class="text-center">Modifier la permission N° {{ $permission->id }}</h3>
        <div>
            <label for="name">Name</label>
            <input type="text" name="name" id="name" value="{{ old('name', $permission->name) }}">
        </div>
        <div>
            <input class="btn btn-primary" type="submit" value="Modifier">
        </div>
    </form>
    <div>
        @if ($errors->any())
            <ul>
                @foreach ($errors->all() as $er)
                    <li>{{ $er }}</li>
                @endforeach
            </ul>



        @endif
    </div>
</div>
@endsection

resources/views/permissions/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Permissions') }}
        </h2>
    </x-slot>
    <div class="container">
        <div class="d-flex justify-content-between my-3">
            <a href="{{ route('permissions.create') }}" class="btn btn-primary">Ajouter une nouvelle categorie</a>
        </div>
        <table id="tbl" class="table center  align-middle text-center caption-top">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Created At</th>
                <th colspan="2">Actions</th>
            </tr>
            @if (isset($notFound))
                <tr>
                    <td colspan="6">La list est vide <a href="{{ route('permissions.index') }}">Retourner a la
                            list</a></td>
                </tr>
            @else
                @foreach ($permissions as $permission)
                    <tr>
                        <td>{{ $permission->id }}</td>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->created_at }}</td>
                        <td><a class="btn btn-success"
                                href="{{ route('permissions.edit', ['permission' => $permission->id]) }}">Modifier</a>
                        </td>
                        <td>
                            <form action="{{ route('permissions.destroy', ['permission' => $permission->id]) }}"
                                method="POST">
                                @method('DELETE')
                                @csrf
                                <input class="btn btn-danger" type="submit" value="Supprimer"
                                    onclick="return confirm('voulez-vous supprimer cette permission?')">
                            </form>
                        </td>
                    </tr>
                @endforeach
        </table>
        {{-- <div>
            {{ $roles->links() }}
        </div> --}}
        @endif
    </div>
</x-app-layout>