routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserRoleController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RolePermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::resource('roles', RoleController::class);
    Route::get('roles/{role}/assign-permissions', [RolePermissionController::class, 'index'])->name('roles.show');
    Route::post('roles/{role}/assign-permissions', [RolePermissionController::class, 'assign'])->name('roles.assign-permissions');

    Route::resource('permissions', PermissionController::class);
    Route::get('/assign-role', [UserRoleController::class, 'index'])->name('user_roles.index');
    Route::get('{user}/assign-role', [UserRoleController::class, 'create'])->name('user_roles.create');
    Route::post('/{user}/assign-role', [UserRoleController::class, 'assignRoles'])->name('user_roles.store');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

});

require __DIR__ . '/auth.php';

app/Http/Controllers/UserRoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class UserRoleController extends Controller
{
    public function index(User $user)
    {
        $roles = Role::all();
        $userRoles = $user->roles;
        return view('user_roles.index', compact('roles', 'user', 'userRoles'));
    }
    public function assignRoles(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'roles' => 'required|array',
            'roles.*' => 'exists:roles,id',
        ]);
        $roles = Role::whereIn('id', $validatedData['roles'])->get();
        $user->syncRoles($roles);
        return redirect()->route('users.index')->with('success', 'Les rôles de l\'utilisateur ont été
modifiés avec succès.');
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/user_roles/create.blade.php
@extends('layouts.layout')
@section('title','Ajouter une role')
@section('space-work')
<div class="container">
    <h1>Créer une nouvelle role</h1>
    <form action="{{route('user_roles.store', ['user' => $user->id])}}" method="POST">
        @csrf
        <div>
        <label for="name">User:</label>
        <input type="text" name="name" id="name" value="{{$user->name}}">
        </div>
        <div class="row">
            <div class="col-md-6">
                <h5>Roles disponibles</h5>
                <ul>
                    @foreach ($roles as $role)
                        @if (!$user->hasRole($role->name))
                            <li>
                                <label>
                                    <input type="checkbox" name="roles[]" value="{{ $role->id }}">
                                    {{ $role->name }}
                                </label>
                            </li>
                        @endif
                    @endforeach
                </ul>
            </div>

            <div class="col-md-6">
                <h5>Roles assignées</h5>
                <ul>
                    @foreach ($roles as $role)
                        @if ($user->hasRole($role->name))
                            <li>
                                <label>
                                    <input type="checkbox" name="roles[]" value="{{ $role->id }}" checked>
                                    {{ $role->name }}
                                </label>
                            </li>
                        @endif
                    @endforeach
                </ul>
            </div>
        </div>

        <div>
            <input class="button" type="submit" value="Assign">
        </div>
    </form>
    <div>
        @if($errors->any())
        <ul>
          @foreach($errors->all() as $er)
           <li>{{$er}}</li>

           @endforeach
        </ul>



        @endif
    </div>
</div>
@endsection

resources/views/user_roles/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>
    <div class="container">
        {{-- <div class="d-flex justify-content-between my-3">
            <a href="{{ route('roles.create') }}" class="btn btn-primary">Ajouter une nouvelle categorie</a>
        </div> --}}
         <table id="tbl" class="table center  align-middle text-center caption-top">
            <tr>
                <th>User</th>
                <th>Role</th>
                <th>Action</th>
            </tr>
            @if (isset($notFound))
            <tr>
               <td colspan="6">La list est vide <a href="{{ route("roles.index") }}">Retourner a la list</a></td>
            </tr>
            @else
            @foreach ($users as $user)
                <tr>
                    <td>{{ $user->name }}</td>
                    <td>
                        @foreach ($user->roles as $role)
                            {{ $role->name }},
                        @endforeach
                    </td>
                    <td><a class="btn btn-success" href="{{ route('user_roles.create', ['user' => $user->id]) }}">Assign Role</a></td>
                </tr>
            @endforeach
        </table>
        {{-- <div>
            {{ $roles->links() }}
        </div> --}}
        @endif
    </div>
</x-app-layout>